apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: rabbitmq-sit
  namespace: sit
spec:
  timeoutSec: 240
  connectionDraining:
    drainingTimeoutSec: 60
  healthCheck:
    type: HTTP  
    requestPath: /
