apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-sit-secret
  namespace: sit
type: Opaque
data:
  RABBITMQ_DEFAULT_USER: 'YWRtaW4='
  RABBITMQ_DEFAULT_PASS: 'YWRtaW4='
  RABBITMQ_ERLANG_COOKIE: 'cmFiYml0bXEjX3Bhc3N3b3Jk'
