apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmq-sit-pv-volume
  labels:
    app: rabbitmq-sit
spec:
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/var/lib/rabbitmq/mnesia/"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-sit-pv-claim
  labels:
    app: rabbitmq-sit
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
